test/cosmoz-bottom-bar.html
@nomego Have a look to test cases.Meanwhile I am adding more test cases
=> Added new test cases for api's

README.md, bower.json
@nomego Have a look to this documentation
=> Chore:Added documentation for using it

cosmoz-bottom-bar.js
=> Set visible property to true

demo/table-test.html
=> Adding cosmoz-omnitable name attribute to demo

cosmoz-bottom-bar.html, cosmoz-bottom-bar.js
An extra slot created for extra menu etc
=> extra slot added

.codeclimate.yml, .eslintignore, .gitignore, .travis.yml, bower.json, cosmoz-bottom-bar-style.html, cosmoz-bottom-bar-view.js, cosmoz-bottom-bar.html, cosmoz-bottom-bar.js, package.json, wct.conf.json, yarn.lock
fixes https://github.com/Neovici/cosmoz-bottom-bar/issues/22
=> Tests code coverage

cosmoz-bottom-bar.js
fixes https://github.com/Neovici/cosmoz-bottom-bar/issues/24
=> cancel debouncer layoutActions

cosmoz-bottom-bar.js
Sets display none on cosmoz-bottom-bar when hidden
Fixes Neovici/cosmoz-omnitable#216
=> Sets display none on cosmoz-bottom-bar when hidden

demo/helpers/x-view.html, test/helpers/fixed-size-item.html
- Convert to Polymer 2.4+ (template getter):
-- demo/helpers/x-view
-- test/helpers/fixed-size-item
Signed-off-by: Patrik Kullman <patrik.kullman@neovici.se>
=> Drop Polymer() 1.x calls

demo/helpers/x-view.html
Demo, ESLint fixes - max-len.
Issue is https://github.com/Neovici/cosmoz-frontend/issues/815.
=> Demo, ESLint fixes - max-len

cosmoz-bottom-bar-view.js, cosmoz-bottom-bar.js
https://github.com/Neovici/cosmoz-frontend/issues/1314
=> (patch) modulizer erroneously escaped `attr$=` to `attr\$=`

.github/workflows/workflow.yml, cosmoz-bottom-bar-view.js, cosmoz-bottom-bar.js
* Added named slot in cosmoz-bottom-bar-view to reach the extra slot in cosmoz-bottom-bar.
* Added CSS rules for toolbar to apply for extraSlot aswell.
* Issue is RM:19734.
**Wait with merge until OK to do so**
=> cosmoz-bottom-bar-view: added named slot

cosmoz-bottom-bar-view.js, cosmoz-bottom-bar.js
Correcting indentation for comments, sorting functions.
=> fix: correcting indentation for comments, sorting functions

package-lock.json, package.json
The package version and the tagged version are mismatched.
=> fix: correct package version

cosmoz-bottom-bar.js, test/cosmoz-bottom-bar.html
Reduce the number of toolbar items from 3 to 1.
Issue is RM:19734.
=> fix: reduce max toolbar items from 3 to 1

cosmoz-bottom-bar-view.js, cosmoz-bottom-bar.html.js
Remove iron-flex-layout from cosmoz-bottom-bar and add  small css/flex fixes
=> fix: remove iron-flex-layout

lib/use-bottom-bar-view.js, test/cosmoz-bottom-bar-view.test.js
Fixes https://neovici.slack.com/archives/C6LJQMJFM/p1597908288006100
=> fix: on desktop bottom-bar remains inactive, if not explicitly made active

cosmoz-bottom-bar-view.js, cosmoz-bottom-bar.html.js, cosmoz-bottom-bar.js, lib/use-bottom-bar-view.js, shell.nix, test/cosmoz-bottom-bar-view.test.js, test/cosmoz-bottom-bar.test.js
* Animates cosmoz-bottom-bar-view's height -> a more visually fluid animation
* Restore cosmoz-bottom-bar hidden resize handling (reverted #87 )
=> Restore cosmoz-bottom-bar-view & cosmoz-bottom-bar behaviors

cosmoz-bottom-bar.html.js, cosmoz-bottom-bar.js, package-lock.json, test/cosmoz-bottom-bar.test.js
- slot the menu items without computing sizes
- sort the menu items by dataset.index
- add hover effect on dropdown slotted actions
- auto width increase (up to 300px)
=> feat(cosmoz-bottom-bar): slot items without computing sizes

cosmoz-bottom-bar.js
=> fix(cosmoz-bottom-bar): resize dropdown on layout

cosmoz-bottom-bar.html.js, cosmoz-bottom-bar.js, package-lock.json, package.json, test/cosmoz-bottom-bar.test.js
Replace paper elements with cosmoz-dropdown
=> feat(bottom-bar): replace paper elements with cosmoz-dropdown

cosmoz-bottom-bar.html.js, package-lock.json
Improve dropdown and actions in bottom-bar styling.
=> feat: dropdown styling

cosmoz-bottom-bar.js
Remove code related to the removed `action` event.
=> feat: remove action event

cosmoz-bottom-bar.html.js
Adds disabled stated for toolbar items
=> fix: disabled toolbar item

package-lock.json, package.json, web-dev-server.config.mjs
BREAKING CHANGE: Upgrade to lit-html@^2
=> feat: uprade to lit-html@^2

.github/workflows/workflow.yml, cosmoz-bottom-bar.html.js, cosmoz-bottom-bar.js, package-lock.json, package.json
=> Implement hide-actions

cosmoz-bottom-bar.js, package-lock.json, package.json
The initial show/hide should happen without a transition.
=> feat(cosmoz-bottom-bar): init without transition

.vscode/settings.json
=> fix(vscode-settings): change eslint settings

cosmoz-bottom-bar.html.js
Add z-index to make bottom-bar appear above content in all views
=> fix: add z-index to make sure bottom-bar is above views content

cosmoz-bottom-bar.html.js, package-lock.json, package.json
Add a info part on the `#info` element allowing styling from outside
=> feat: add a info part

src/overflow.ts
[AB#18626](https://dev.azure.com/neovici/7e94365d-32b1-416f-854b-7f195da31da6/_workitems/edit/18626)
=> fix(overflow): nested slots are not handled properly

src/overflow.ts
[AB#18676](https://dev.azure.com/neovici/7e94365d-32b1-416f-854b-7f195da31da6/_workitems/edit/18676)
1. Now we properly clean up old elements upon `slotchange`
2. Changed logic for deciding the visibility of an element to not take into consideration the total intersectionRatio, as that accounted for vertical visibility. We are only interested in horisontal visibility/overflow for this directive.
=> fix(overflow): old elements did not clean up on slotchange and visibility check took into consideration vertical visibility

src/overflow.ts
[AB#18626](https://dev.azure.com/neovici/7e94365d-32b1-416f-854b-7f195da31da6/_workitems/edit/18626)
=> fix(overflow): hidden elements are considered visible

src/cosmoz-bottom-bar.ts, src/overflow.ts
[AB#18626](https://dev.azure.com/neovici/7e94365d-32b1-416f-854b-7f195da31da6/_workitems/edit/18626)
=> fix: new overflowing elements flicker

package-lock.json, src/cosmoz-bottom-bar.ts, test/cosmoz-bottom-bar.test.js
Adjust hidden/overflowing state.
=> feat(bottom-bar): adjust hidden/overflowing state
